version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_PORT=5432
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=admin
    command: ["start-dev"]
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=keycloak
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  neo4j-db:
  db:
